start: instruction+

instruction: "backup" PATH ":to:" PATH  [":" (avg_time_expresion | precise_time_expression | change_expression)]

PATH : ("a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"|"n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|"0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"."|"/"|"\\"|" "|"_")+

avg_time_expresion : "every" avg_time_expresion_suffix
avg_time_expresion_suffix : "hour"             -> every_hour
                | NUMBER "hours"               -> every_nb_hours
                | "minute"                     -> every_minute
                | NUMBER "minutes"             -> every_nb_minutes

precise_time_expression : "at" NUMBER ":" NUMBER

change_expression : "on every change"

NUMBER: ("0".."9")+

WHITESPACE: (" " | "\n")+
%ignore WHITESPACE
